### ISSUE TITLE
`Parser("Incomplete(Size(513))")` Error from `der::from_slice`

### ISSUE THREAD

**Issue by chocol4te** [dac-gmbh/asn1#17]
I have a minimal failing example [here](https://github.com/chocol4te/asn1-minimal-failing).

Encoding always succeeds, but if the length of a `Vec` in a structure to be decoded exceeds a certain size, I get the error in the title.

Per the example, if the length of the `Vec` is 85, it works without issue, but panics if the length is 86.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! The problem was the long length encoding was correct but the order of the bytes needed to be flipped. I've fixed this and put in a test to prevent this happening in the future.

I'll add a `CONTRIBUTING.md` with more details, but `asn1` does have logging and if you enable `debug` level logging the encoder will output a hexadecimal version of the encoding, which is more helpful as I can use the [JavaScript ASN.1 decoder](https://lapo.it/asn1js/) to debug the issue quicker than a minimal example.

**Comment by chocol4te** [comment]
https://github.com/dac-gmbh/asn1/blob/dbfc40a4137602829a761fe14c0371abba9092ec/asn1-der/src/encoder.rs#L91

I think a `dbg!` slipped through...

**Comment by XAMPPRocky** [comment]
Fixed
