### ISSUE TITLE
`None` should not be skipped by the serializer

### ISSUE THREAD

**Issue by jonas-schievink** [dac-gmbh/asn1#24]
```rust
    #[test]
    fn option() {
        #[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
        struct Struct {
            a: Option<u8>,
            b: Option<u8>,
        }

        let data = Struct { a: None, b: Some(100) };

        assert_eq!(data, from_slice(&to_vec(&data).unwrap()).unwrap());
    }
```

fails with:

```
thread 'tests::option' panicked at 'assertion failed: `(left == right)`
  left: `Struct { a: None, b: Some(100) }`,
 right: `Struct { a: Some(100), b: None }`', asn1-der/src/lib.rs:223:9
```

This happens because `None` is skipped by the serializer, so the deserializer cannot tell the difference between `None` followed by `Some` and `Some` followed by `None`. `None` should probably be encoded as a `()` instead of being ignored.

**Comment by XAMPPRocky** [comment]
This is intentional, and a bug in the decoder where it does not distingush fields. To be legal you are generally required to tag these types (or have a compiler tag them for you), and the decoder should be able to put it in the right field. I'm going to accept this as a temporary workaround however.

**Comment by jonas-schievink** [comment]
Ah I see. Would be good to open issues for these kinds of bugs, since changing how things are encoded is breaking any consumers (ie. our embedded devices).
